name: Checkout Workflow
on:
  push:
jobs:
  checkout:
    name: "Checkout Job"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
    - name: "README.md content"
      run: cat Readme.md
